function TxchirpSequences =   ...
        ChirpSpreadSpectrum_Tx ( incomingStream , dataRate, chirpSequence )
% ----------------------------------------------------------------------- %
% ======================================================================= %
% ChirpSpreadSpectrum_Tx  : Function Summary
% ======================================================================= %
% ----------------------------------------------------------------------- %
% The stream of payload binary bits is modulated to DQPSK symbols then the 
% DQPSK symbols shall be modulated onto the stream of 
% subchirps that is generated by the chirp-shift keying (CSK) generator. 
% ======================================================================= %
% Get the global variables
% ----------------------------------------------------------------------- %
global SFD_Std ;
global SFDlength ;
global PHRlength ;
global preambleLengthStd ;
global numBitsPerCodeWordStd ;

global codeWordLengthStd ;
global codeword_1Mbs;
global codeword_250kbs;
%-------------------------------------------------------------------------%
%-------------------------------------------------------------------------%
if dataRate == 0 
    % dataRate ... 0 for  1 Mb/s  , 1  for 250 kb/s
    %---------------------------------------------------------------------%
    % The preamble for 1 Mb/s consists of 8 chirp symbols, ones(0:31).
    preambleLength = preambleLengthStd(1);
    %     1 Mb/s Code Word Length
    codeWordLength = codeWordLengthStd(1) ;
    % codeword(c0, c1, c2, c3) for the 1 Mb/s data rate as in Table26a. 
    codeword = codeword_1Mbs;
    %      1 Mb/s Number of bits per Code Word
    numBitsPerCodeWord = numBitsPerCodeWordStd(1);
    %---------------------------------------------------------------------%
else
    %---------------------------------------------------------------------%
    % The preamble for 250 kb/s consists of 20 chirp symbols, ones(0:79).
    preambleLength = preambleLengthStd(2);
    %     250 kb/s Code Word Length
    codeWordLength = codeWordLengthStd(2) ;
    % codeword (c0, c1, c2, ... , c31) for the optional 250 kb/s data rate 
    % as specified in Table 26b.
    codeword = codeword_250kbs;
    %     250 kb/s Number of bits per Code Word
    numBitsPerCodeWord = numBitsPerCodeWordStd(2);
    %---------------------------------------------------------------------%
end
%-***********************************************************************-%
payloadLength = length(incomingStream)/8;
%-------------------------------------------------------------------------%
%=========================================================================%
%  6.5a.3.1 Preamble
%=========================================================================%
%-------------------------------------------------------------------------%
% The preamble sequence from Table 26d should be applied directly to both
% I input and the Q input of QPSK.as specified in Table 26d.
% codeWordLength represent number of chip/symbol 
if dataRate == 0 
    %---------------------------------------------------------------------%
    % The preamble for 1 Mb/s consists of 8 chirp symbols, ones(0:31).
    preamble = ones(1,preambleLength);
     %---------------------------------------------------------------------%
else
    %---------------------------------------------------------------------%
    % The preamble for 250 kb/s consists of 20 chirp symbols, ones(0:79).
     preamble = ones(1,preambleLength);
     %---------------------------------------------------------------------%
end
%-***********************************************************************-%
%-------------------------------------------------------------------------%
%=========================================================================%
%  6.3.2 SFD field
%=========================================================================%
%-------------------------------------------------------------------------%
% Start-of-frame delimiter (SFD) bit sequences for the CSS PHY type are 
% defined in Table 20a. Different SFD sequences are defined for the two 
% different data rates.
% A SFD sequence from Table 20a shall be applied directly to both inputs 
% (I and Q) of the QPSK mapper. A SFD sequence starts with bit 0.
if dataRate == 0 
    % The SFD for 1 Mb/s. 
    SFD = SFD_Std (1,:);
else
    % The SFD for 250 kb/s.
    SFD = SFD_Std (2,:);
end
%-***********************************************************************-%
%-------------------------------------------------------------------------%

%-------------------------------------------------------------------------%
%=========================================================================% 
% 6.5a.3.3 PHY header (PHR)
%=========================================================================%
%-------------------------------------------------------------------------%
% The format of the PHR is shown in Figure 20b.
% Bit 0 ... Bit 6  ..... Length of payload
% payloadLength_Binary = de2bi (payloadLength,7);
payloadLength_Binary(7:-1:1) = decimal2binary(payloadLength,7,1); 
% Bit 7 ... Bit 8  ..... not used
not_used = [0 0];
% Bit 9 ... Bit 11 ..... reserved
reserved = [0 0 0];
% 1 Mb/s (r=3/4)   ....  PHR  12/4 = 4 symbols
% 250 kb/s (r=6/32) .... PHR  12/6 = 2 symbols
PHR = [payloadLength_Binary,not_used,reserved];
%-***********************************************************************-%
%-------------------------------------------------------------------------%
%=========================================================================%
% 6.5a.2.1 Reference modulator diagram
%=========================================================================%
%-------------------------------------------------------------------------%
preamble_SFD = [preamble,SFD];
% All binary data contained in the PHR and PSDU shall be encoded using the
% modulation shown in Figure 20a.
binaryData = [PHR,incomingStream];
%-***********************************************************************-%
%-------------------------------------------------------------------------%
% ###################### file Input Output ############################## %
% fid = fopen('preambleSFD.txt', 'wt' );
% fprintf(fid, '%d%d%d%d\n', fliplr (transpose((preamble_SFD+1)/2)));
% fclose (fid);
% ###################### file Input Output ############################## %
%-------------------------------------------------------------------------%

%-------------------------------------------------------------------------%
%-------------------------------------------------------------------------%
%=========================================================================%
% Padding the incoming stream to make sure it fits into the Symbol Mapper 
%=========================================================================%
%-------------------------------------------------------------------------%
if dataRate == 0   % 1 Mb/s  
    %---------------------------------------------------------------------%
    % The padding for 1 Mb/s . 2(I,Q) * 3 bit per dataSymbol = 6 bits.
    paddingBy = 6 - mod(payloadLength*8 + PHRlength, 6);
    %---------------------------------------------------------------------%
else  % 250 kb/s
    %---------------------------------------------------------------------%
    % The data stream going into the interleaver shall be padded with zeros
    % if the number of octets to be transmitted does not align with the 
    % bounds of the interleaver blocks.
    % The interleaver permutes the chips across two consecutive codewords 
    % for each of I and Q, independently. 
    % The padding for 250 kb/s .
    % 2(I,Q) * 2( consecutive codewords ) * 6 bit per dataSymbol = 24 bits.
    paddingBy = 24 - mod(payloadLength*8 + PHRlength , 24); 
    %---------------------------------------------------------------------%
end
%-------------------------------------------------------------------------%
%-------------------------------------------------------------------------%
binaryData = [binaryData,zeros(1,paddingBy)];
% % ###################### file Input Output ############################## %
paddingfile = 8 - mod(length (binaryData),8);
binaryData2file = [ binaryData, zeros(1,paddingfile) ];
fid = fopen('payload.txt', 'wt' );
payloadtoFile = transpose ( fliplr ((transpose ( reshape (binaryData2file,8,[]) ))));
fprintf(fid,'%d%d%d%d%d%d%d%d\n', payloadtoFile(1 : end) );
fclose (fid);
% ###################### file Input Output ############################## %

%-***********************************************************************-%
%-------------------------------------------------------------------------%
%=========================================================================%
% 6.5a.2.2 De-multiplexer (DEMUX)
%=========================================================================%
%-------------------------------------------------------------------------%
% For each packet, the first bit of the incoming stream of information bits
% of a packet shall be switched to the
% I path, and the second bit shall be switched to the Q path and So on.
binaryDataLengthBits=payloadLength*8 + paddingBy + PHRlength;
I = binaryData (1:2:binaryDataLengthBits-1);
Q = binaryData (2:2:binaryDataLengthBits);
%-***********************************************************************-%
%-------------------------------------------------------------------------% 
%=========================================================================%
% 6.5a.2.3 Serial-to-parallel mapping (S/P)
%=========================================================================%
%-------------------------------------------------------------------------%
% By using two serial-to-parallel converters, the substreams are 
% independently partitioned into sets of bits to form data symbols.

numCodeWords=binaryDataLengthBits/2/numBitsPerCodeWord;
% data rate of 1 Mb/s, a data symbol shall consist of three bits.
% i.e.,numBitsPerCodeWord=3.
% data rate of 250 kb/s, a data symbol shall consist of 6 bits.
% i.e.,numBitsPerCodeWord=6.
I_path = reshape (I,numBitsPerCodeWord, numCodeWords)';
Q_path = reshape (Q,numBitsPerCodeWord, numCodeWords)';
    
% the binary data symbol (b0,b1,b2), the first input data bit for each of 
% I and Q is assigned b0, and the third input data bit is assigned b2. 
% For the optional data rate the binary data symbol (b0,b1,b2,b3,b4,b5), 
% the first input data bit for each of I and Q is assigned b0,
% and the sixth input data bit is assigned b5.
% Note that here we follow the noation of the first column of table 
% 26a& 26b,not the middle column. It makes no difference as long as we are
% consistent when we do the mapping from the tables
% Note : replace bi2de with dinary2decimal developed function upon 
% customer request
% I_path_decimal = bi2de (I_path,'left-msb'); % Serial-to-parallel mapping
I_path_dec = binary2decimal(I_path,numBitsPerCodeWord,numCodeWords);
% Q_path_decimal = bi2de (Q_path,'left-msb'); % Serial-to-parallel mapping
Q_path_dec = binary2decimal(Q_path,numBitsPerCodeWord,numCodeWords);

%-***********************************************************************-%
%-------------------------------------------------------------------------%
%=========================================================================%
% 6.5a.2.4 Data-symbol-to-bi-orthogonal-codeword mapping
%=========================================================================%
%-------------------------------------------------------------------------%
% Bi-orthogonal mapping
% 1 Mb/s , Each 3-bit data symbol shall be mapped onto a 4-chip
% bi-orthogonal (code rate = 3/4)
% 250 kb/s , Each 6-bit data symbol shall be mapped onto a 32-chip 
% bi-orthogonal (code rate = 3/16)

% for i = 1 : length (I_path_dec)
%     I_path_mapped_biOrthogonal(i,:)= codeword(I_path_dec(i)+1,:); 
%     Q_path_mapped_biOrthogonal(i,:)= codeword(Q_path_dec(i)+1,:); 
% end 
global I_path_mapped_biOrthogonal;
global Q_path_mapped_biOrthogonal;

I_path_mapped_biOrthogonal=(codeword(I_path_dec+1,:));
Q_path_mapped_biOrthogonal=(codeword(Q_path_dec+1,:));
%-***********************************************************************-%
%-------------------------------------------------------------------------%
%=========================================================================%
% 6.5a.2.9 Bit interleaver
%=========================================================================%
%-------------------------------------------------------------------------%
% The bit interleaver is applied only for the optional data rate of 250kb/s
% The 32 chip bi-orthogonal codewords for the optional 250 kb/s data rate 
% are interleaved prior to the parallel to serial converter.
if dataRate == 1
%-------------------------------------------------------------------------%
    % The interleaver permutes the chips across two consecutive codewords  
    % for each of I and Q, independently.
    % ------------------------------------------------------------------- %
    I_path_mapped_biOrthogonal = ...
                bitInterleaver (I_path_mapped_biOrthogonal , numCodeWords);
    Q_path_mapped_biOrthogonal = ...
                bitInterleaver (Q_path_mapped_biOrthogonal , numCodeWords);
    % ------------------------------------------------------------------- %
else
    % ------------------------------------------------------------------- %
    I_path_mapped_biOrthogonal=transpose(I_path_mapped_biOrthogonal);
    Q_path_mapped_biOrthogonal=transpose(Q_path_mapped_biOrthogonal);
    % ------------------------------------------------------------------- %
end
%-***********************************************************************-%
%-------------------------------------------------------------------------%
%=========================================================================%
% 6.5a.2.5 Parallel-to-serial converter (P/S) and QPSK symbol mapping
%=========================================================================%
%-------------------------------------------------------------------------%
% Parallel-to-serial converter (P/S)
%-------------------------------------------------------------------------%

% Each bi-orthogonal codeword shall be converted to a serial chip sequence.
% Within each 4-chip codeword (c0, c1, c2, c3) for the 1 Mb/s data rate, 
% the least significant chip c0 is processed first,and the most significant
% chip c3 is processed last for I and Q, respectively. 

% Within each 32-chip codeword (c0, c1,c2, ... , c31) for the 250 kb/s 
% data rate, the least significant chip c0 is processed first, and the most 
% significant chip c31 is processed last for I and Q, respectively.
I_path_binaryData = ...
    reshape(I_path_mapped_biOrthogonal,1,codeWordLength*numCodeWords);
Q_path_binaryData = ...
    reshape(Q_path_mapped_biOrthogonal,1,codeWordLength*numCodeWords);
%-------------------------------------------------------------------------%
% Preamble,SFD sequence shall be applied directly to both inputs 
% (I and Q) of the QPSK mapper.
I_path = [preamble_SFD,I_path_binaryData]';
Q_path = [preamble_SFD,Q_path_binaryData]';
%-------------------------------------------------------------------------%
% QPSK symbol mapping
%-------------------------------------------------------------------------%
% QPSK_InputChips mapping;
% Each pair of I and Q chips shall be mapped onto a QPSK symbol 
% as specified in Table 26c.
global DQPSK_input;
DQPSK_input= ((I_path +  Q_path) - j*(I_path -  Q_path))/2;
%-***********************************************************************-%
%-------------------------------------------------------------------------%
%=========================================================================%
% 6.5a.2.6 DQPSK coding
%=========================================================================%
%-------------------------------------------------------------------------%
% The stream of QPSK symbols shall be differentially encoded by using a 
% differential encoder with a QPSK symbol feedback memory of length 4. 
% For every packet, the initial values of all four feedback memory stages 
% of the differential encoder shall be set to exp(j*pi/4)
feedback_memory = ones(4,1) + 1i*ones(4,1) ;

% (In other words, the phase summtion between QPSK symbol 1 and 5, 2 and 
% 6, 3 and 7, 4 and 8, and so on are computed.)

numDQPSKinputs= binaryDataLengthBits /2 *codeWordLength / ... 
                          numBitsPerCodeWord + preambleLength + SFDlength;
%-------------------------------------------------------------------------%                      
for i =1: 4 : numDQPSKinputs
    %---------------------------------------------------------------------%
    DQPSK_output(i:i+3,1) =  DQPSK_input(i:i+3,1) .* feedback_memory ;
    % QPSK_symbols Stored in feedback memory 
    feedback_memory = DQPSK_output(i:i+3);
    
    %---------------------------------------------------------------------%
end
%-------------------------------------------------------------------------%
% DQPSK output must be normalized. In reality, only the phase is needed. 
% It can be represented in units of PI and added to the complex phase when
% doing chirp modulation
% ####################################################################### %
% Transmitter Fixed Point ... removing the normalization.
% ####################################################################### %
% DQPSK_output = DQPSK_output/sqrt(2);
%-------------------------------------------------------------------------%
%=========================================================================%
% 6.5a.2.7 DQPSK-to-DQCSK modulation
%=========================================================================%
%-------------------------------------------------------------------------%
% The stream of DQPSK symbols shall be modulated onto the stream of 
% subchirps that is generated by the chirp-shift keying (CSK) generator. 
% The effect of the differential quadrature chirp-shift keying (DQCSK) 
% modulation shall be that each subchirp is multiplied with a DQPSK value 
% that has unit magnitude and has constant phase for the duration of the 
% subchirp

 TxchirpSequences = ...
        chirpModulation( DQPSK_output , chirpSequence );
%-***********************************************************************-%
%-***********************************************************************-%
end
%-------------------------------------------------------------------------%
%-***********************************************************************-%
%-***********************************************************************-%
