function [ chirpSymbols ] = ...
                            chirpModulation( QPSKsymbols, chirpSequence )
% ----------------------------------------------------------------------- %
% ======================================================================= %
% chirpModulation  : Function Summary
% ======================================================================= %
% ----------------------------------------------------------------------- %
% The stream of DQPSK symbols shall be modulated onto the stream of 
% subchirps that is generated by the chirp-shift keying (CSK) generator. 
% The effect of the differential quadrature chirp-shift keying (DQCSK) 
% modulation shall be that each subchirp is multiplied with a DQPSK value 
% that has unit magnitude and has constant phase for the duration of the 
% subchirp
% ======================================================================= %
% Get the global variables
% ----------------------------------------------------------------------- %
global Tchirp;
global Tsub;
global Tgap ;
% ----------------------------------------------------------------------- %
% make sure the input is a row vector
[x y]=size(QPSKsymbols);
if x>1
   QPSKsymbols=transpose(QPSKsymbols); 
end
% ----------------------------------------------------------------------- %
numQPSKsymbols=length(QPSKsymbols);
% ----------------------------------------------------------------------- %
%Prepare a zero array for the output. This saves run time considerably
chirpSymbols=zeros(1,numQPSKsymbols/4*Tchirp);
% ----------------------------------------------------------------------- %
% ----------------------------------------------------------------------- %
% Start modulating the chirp sequence and adding gaps 
% ----------------------------------------------------------------------- %
startIndex=0;
for QPSKgroupCounter=0:numQPSKsymbols/4-1
    % ------------------------------------------------------------------- %
    % Capture 4 DQPS symbols
    % ------------------------------------------------------------------- %
    groupIndex=(4*QPSKgroupCounter+1 : 4*QPSKgroupCounter+4);
    modulationSymbols=repmat(QPSKsymbols(groupIndex), Tsub ,1);
    
    evenOdd=mod(QPSKgroupCounter,2);
    % ------------------------------------------------------------------- %
    % Modulate the 4 subchrip sequence with the 4 DQPSK symbols
    % Then, reshape and produce one sequence
    % ------------------------------------------------------------------- %
    tmp= reshape(chirpSequence .* modulationSymbols , 1, 4*Tsub);
    % ------------------------------------------------------------------- %
    % Calculate the time gap after this chirp sequence. The gap varies in
    % even and odd sequences
    chirpSymbolLength= 4*Tsub + Tgap(evenOdd+1); % equal to length(tmp)
    % ------------------------------------------------------------------- %
    % concatenate the chip sequences
    % ------------------------------------------------------------------- %
    chirpSymbols(1+startIndex: startIndex + 4*Tsub)= tmp;
                        
    startIndex=startIndex + chirpSymbolLength;
%-***********************************************************************-%
%-***********************************************************************-%
end
end



