% ----------------------------------------------------------------------- %
% ----------------------------------------------------------------------- %
global css_tx_real;
global css_tx_imag;
css_tx_real = zeros(1,TxChirpSequencesLength);
css_tx_imag = zeros(1,TxChirpSequencesLength);
% ----------------------------------------------------------------------- %
% ----------------------------------------------------------------------- %
cd ./../../VHDL 
hdldaemon('kill');
hdldaemon('socket',1225);
%  'add wave sim:/css_tx/*',...
%  'add wave sim:/css_tx/css_unit/enable ',...
%  'add wave sim:/css_tx/css_unit/Tgap',...
%  'add wave sim:/css_tx/css_unit/Tx_done',...
%  'add wave sim:/css_tx/css_unit/counter',...
vsim('tclstart', ...
{'vmap work work',...
 'vcom *.vhd',...
 'vsimmatlab -novopt css_tx',...
 'matlabtb css_tx -mfunc css_tx.m -socket 1225 -rising  /css_tx/clk',...
 'force -freeze sim:/css_tx/clk 1 0, 0 {50 ns} -r 100',...
 'force -freeze sim:/css_tx/reset 1 0',...
 'run 600',...
 'force -freeze sim:/css_tx/reset 0 0',...
 'run 100',...
 'force -freeze sim:/css_tx/start_tx 1 0',...
 'run 7872000'});
cd ./../MATLAB/CSS_TxRxFullV15.01_Fixed
% ----------------------------------------------------------------------- %
% ----------------------------------------------------------------------- %
real_compare = reshape ( [real(TxchirpSequences)  css_tx_real(1:length(TxchirpSequences))],[],2);
imag_compare = reshape ( [imag(TxchirpSequences)  css_tx_imag(1:length(TxchirpSequences))],[],2);
realErrors = find (real(TxchirpSequences) ~= css_tx_real(1:length(TxchirpSequences)));
imagErrors = find (imag(TxchirpSequences) ~= css_tx_imag(1:length(TxchirpSequences)));
% -----------------------------------------------------------------------
% ----------------------------------------------------------------------- %